export const itemList = [
  {
    reference: 101,
    image: "../images-fox/shop/item-images/101.png",
    name: "Red fox",
    price: 300,
    rating: "../images-fox/shop/rating/four star.png",
    topic: "Other",
  },
  {
    reference: 102,
    image: "../images-fox/shop/item-images/102.jpg",
    name: "Rat",
    price: 12,
    rating: "../images-fox/shop/rating/three star.png",
    topic: "For kids",
  },
  {
    reference: 103,
    image: "../images-fox/shop/item-images/103.jpg",
    name: "German Dog",
    price: 60,
    rating: "../images-fox/shop/rating/four star.png",
    topic: "Forest",
  },
  {
    reference: 104,
    image: "../images-fox/shop/item-images/104.jpg",
    name: "Labrador",
    price: 30,
    rating: "../images-fox/shop/rating/five star.png",
    topic: "For kids",
  },
  {
    reference: 105,
    image: "../images-fox/shop/item-images/105.jpg",
    name: "Rabbit",
    price: 19,
    rating: "../images-fox/shop/rating/three star.png",
    topic: "For kids",
  },
  {
    reference: 106,
    image: "../images-fox/shop/item-images/106.jpg",
    name: "Parrot",
    price: 135,
    rating: "../images-fox/shop/rating/four star.png",
    topic: "Other",
  },
  {
    reference: 107,
    image: "../images-fox/shop/item-images/107.jpg",
    name: "Hamster",
    price: 20,
    rating: "../images-fox/shop/rating/four star.png",
    topic: "Other",
  },
  {
    reference: 108,
    image: "../images-fox/shop/item-images/108.jpg",
    name: "Racoon",
    price: 110,
    rating: "../images-fox/shop/rating/three star.png",
    topic: "For kids",
  },
  {
    reference: 109,
    image: "../images-fox/shop/item-images/109.jpg",
    name: "Capybara",
    price: 460,
    rating: "../images-fox/shop/rating/five star.png",
    topic: "Forest",
  },
  {
    reference: 110,
    image: "../images-fox/shop/item-images/110.jpeg",
    name: "Beagle",
    price: 170,
    rating: "../images-fox/shop/rating/five star.png",
    topic: "For kids",
  },
  {
    reference: 111,
    image: "../images-fox/shop/item-images/111.png",
    name: "A fox",
    price: 200,
    rating: "../images-fox/shop/rating/five star.png",
    topic: "Forest",
  },
  {
    reference: 112,
    image: "../images-fox/shop/item-images/112.jpg",
    name: "A hen",
    price: 10,
    rating: "../images-fox/shop/rating/three star.png",
    topic: "Other",
  },
];
